module.exports = {
  sex_bonus: {
    sexual_pheromones: 0.2,
    targeted_pheromones: 0.5,
    elastic_orifices: 0.2,
    exhibitionist: 0.1,
    nudist: 0.3,
    sexually_gifted: 0.3,
    soft: 0.2,
    natural_anal_lube: 0.3,
    prehensile_tentacles: 0.4,
    large_breasts: 0.1,
    huge_breasts: 0.2,
    multiple_breasts: 0.1,
    drooling_vagina: 0.3,
    large_penis: 0.2,
    huge_penis: 0.3,
    multiple_penises: 0.3,
    high_volume_ejaculations: 0.3,
    addictive_cum: 0.3,
    adorable: 0.1,
    lewd_mind: 0.2,
    sex_crazed: 0.3,
    seasonal_breeders: -0.3,
    sexually_inept: -0.4,
    sexually_repressed: -0.5,
    small_penis: -0.2,
    opt_intercompatible_womb: 0.2,
    opt_intercompatible_sperm: 0.2,
    sex_bots: 0.5,
    breast_attachments: 0.1,
    synth_breasts: 0.2,
    custom_fleshlight_slot: 0.2,
    synth_vagina: 0.3,
    custom_dildo_attachment: 0.2,
    synth_penis: 0.3,
    artificial_womb: 0.3,
    cybernetic_womb: 0.5,
    biomechanical_breeder: 0.2,
    synth_seeder: 0.4,
  },
  sex_bonus_sexualization_finish: 0.2,
  cow_bonus: {
    nutrient_extrusion: 0.2,
    large_breasts: 0.2,
    huge_breasts: 0.3,
    multiple_breasts: 0.4,
    high_volume_lactation: 0.3,
    highly_nutritious_milk: 0.4,
    drooling_vagina: 0.1,
    litters: 0.2,
    small_breasts: -0.2,
    watery_milk: -0.5,
    breast_attachments: 0.1,
    synth_breasts: 0.2,
  },
  bioreactor_bonus: {
    oviposition: 0.1,
    high_volume_ejaculations: 0.2,
    opt_intercompatible_womb: 0.3,
    opt_intercompatible_sperm: 0.2,
  },
  max_districts: [...new Array(21).keys()].slice(1),
}
